### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bkzutr90** [tfkhdyt/wa-sticker-bot#1]
/root/wa-sticker-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:14:123
    at ExecutionContext._evaluateInternal (/root/wa-sticker-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/root/wa-sticker-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.initialize (/root/wa-sticker-bot/node_modules/whatsapp-web.js/src/Client.js:267:9)
root@iZt4n399yyn07pki1eijsdZ:~/wa-sticker-bot#

**Comment by tfkhdyt** [comment]
Update dependensinya

`pnpm up`

**Comment by tfkhdyt** [comment]
Upstream bug

https://github.com/pedroslopez/whatsapp-web.js/issues/1786#issuecomment-1311578102
